from data_structure import DataElement, GetStrategy
from enum import Enum


class SedohDataSource(Enum):
    ACS = 1


sedoh_data_elements = [
    DataElement(SedohDataSource.ACS, "Gini Inequality Coefficient", "gini_inequality_coefficient", "B19083_001E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Old Age Dependency Ratio", "old_age_dependency_ratio", "S0101_C01_035E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Child Dependency Ratio", "child_dependency_ratio", "S0101_C01_036E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Housing - Median Year Built", "housing_median_year_built", "B25035_001E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units Lacking Plumbing",
                "housing_percent_occupied_units_lacking_plumbing", "S2504_C02_025E", GetStrategy.CALCULATION),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units Lacking Complete Kitchen",
                "housing_percent_occupied_lacking_complete_kitchen", "S2504_C02_026E", GetStrategy.CALCULATION),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units with No Bedroom",
                "housing_percent_occupied_units_with_no_bedroom", "S2504_C02_021E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units with No Vehicle Available",
                "housing_percent_occupied_units_with_no_vehicle_available", "S2504_C02_027E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units with No Computer [includes Smartphone]",
                "housing_percent_occupied_units_with_no_computer_included_smartphone", "S2801_C02_011E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Housing - Percent Occupied Units with No Internet Subscription",
                "housing_percent_occupied_units_with_no_internet_subscription", "S0101_C01_036E",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Population Density", "population_density", "S0101_C01_001E",
                GetStrategy.CALCULATION),
    DataElement(SedohDataSource.ACS, "Percent Hispanic", "percent_hispanic", "DP05_0071PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent American Indian or Alaska Native",
                "percent_american_indian_or_alaska_native", "DP05_0039PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Asian", "percent_asian", "DP05_0044PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Black", "percent_black", "DP05_0038PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Native Hawaiian or Other Pacific Islander",
                "percent_native_hawaiian_or_other_pacific_islander", "DP05_0052PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Multiple Race", "percent_multiple_race", "DP05_0058PE",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent White", "percent_white", "DP05_0037PE", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Some Other Race", "percent_some_other_race", "DP05_0057PE",
                GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Below 100% of Fed Poverty Level",
                "percent_below_100_of_fed_poverty_level", "S1701_C03_001E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Below 200% of Fed Poverty Level",
                "percent_below_200_of_fed_poverty_level", "...", GetStrategy.CALCULATION),
    DataElement(SedohDataSource.ACS, "Percent Below 300% of Fed Poverty Level",
                "percent_below_300_of_fed_poverty_level", "...", GetStrategy.CALCULATION),
    DataElement(SedohDataSource.ACS, "Percent Households that Receive SNAP",
                "percent_households_that_receive_snap", "S2201_C04_001E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Households with Limited English",
                "percent_households_with_limited_english", "S1602_C04_001E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent High School Grad - Age 25 or Over",
                "percent_households_with_limited_english", "S1501_C02_009E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Percent Bachelor's Degree - Age 25 or Over",
                "percent_bachelors_degree_age_25_or_over", "S1501_C01_012E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Median Household Income",
                "median_household_income", "B19013_001E", GetStrategy.PUBLIC_API),
    DataElement(SedohDataSource.ACS, "Unemployment Rate - Age 16 or Over",
                "unemployment_rate_age_16_or_over", "DP03_0005PE", GetStrategy.PUBLIC_API),
]
