# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Executable Command

on:
  - push

jobs:
  update-executable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Update Executable
      run: |
        pip install pyinstaller
        pyinstaller main.spec
        git add main.exe --force
        git commit
#        mv dist/main enhance.exe