# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Executable Command

on:
  - push

jobs:
  linux-executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"
      - name: Install Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: "true"
      - name: Check Rasterio Dir
        run: |
          find / -type d -name "rasterio"
      - name: Update Executable
        run: |
          pip install pyinstaller
          pyinstaller --distpath ./executables --specpath ./specs/main_lin.spec --name enhance_lin
          git config --global user.name 'Hakob Abajian'
          git config --global user.email 'hakob.abajian@med.usc.edu'
          git add main.exe --force
          git commit -m "Updated Executable"
          git push